### ISSUE TITLE
Control Multiple GPIOs on ESP-12

### ISSUE THREAD

**Issue by jemarr** [torinnguyen/ESP8266Wemo#1]
Thanks for your amazing project.

I've several ESP8266 (ESP-12E) boards controlling a lot of relays that turn on/off my home lamps...and sensors that reads luminosity. Each writen with his own arduino sketch.

Now it's the time to buy an Amazon Echo and your project could help me a lot.

I use several GPIOs on each ESP-12E board, so, is it possible to modify your project to make the Echo detect multiple devices as Fauxmo does instead of just one ???

Thanks for your help.

**Comment by torinnguyen** [comment]
That can be done. Here's the steps:
- Modify responseToSearchUdp function, use a for-loop to give 1 response for each GPIO pin you want to control. Each pin must be assign a unique serialNumber, uuid & port. (IP Address is the same for all, it is always the IP Address of your ESP8266)
- For each of the port/pin you have setup above, create a ESP8266WebServer for it.
- Modify handleUpnpControl function to handle on/off logic for each different port/webserver.

**Comment by jemarr** [comment]
Hi Torin...

Thank you very much for your answer.... I will try to modify the sketch to control each GPIO as a WeMo switch.

Kind regards

**Comment by cobra85ec** [comment]
hey.. i love ur work on this project... can u post a sample code to control more pins plz... im now to this and dont understand.. thank you

**Comment by torinnguyen** [comment]
My code only supports 1 pin and I have outlined the step how to implement for multiple pins. I can't help you to do the actual coding.

**Comment by cobra85ec** [comment]
can u plz help me out... ill pay u $30.. i only need to pins

**Comment by jemarr** [comment]
cobra85ec,

here:

https://learn.adafruit.com/easy-alexa-or-echo-control-of-your-esp8266-huzzah?view=all

and here:

https://github.com/kakopappa/arduino-esp8266-alexa-multiple-wemo-switch

you have two solutions, both can control up to 8 pins in ESP8266.
