### ISSUE TITLE
ESP8266 turns off very shortly after turning LED or relay on?

### ISSUE THREAD

**Issue by joeman2116** [torinnguyen/ESP8266Wemo#3]
First, Thanks for the excellent work on the Wemo emulator.
I loaded the code after making changes to the wifi info etc and ran it in the browser and told alexa dot gen 2 to look for new devices.
It discovers them perfectly (2)

The only thing I noticed was the Esp8266 turns off the led  or relay after a short period of time.
Typically between 30 and 60 seconds.
I tried the code on several other ESP8266 , which work fine with other coding.  same  results.
I was wondering if any one else has seen this similar problem?

Thanks again
Joe

**Comment by cobra85ec** [comment]
can i pay u $30 plz.... i need 2 pins
