### ISSUE TITLE
Sketch query

### ISSUE THREAD

**Issue by 1rvy** [torinnguyen/ESP8266Wemo#4]
Firstly thanks a million for this sketch, it does exactly what I needed it to do, I am setting up an ESP8266 for Alexa interaction and also basic web functionality for IFTTT and Homebridge to tuern devices on and off.
I have edited your .imo and included a standard web server on port 80 to allow me to turn on and off two pins for different relays, this works well.
Your original script works with Alexa and I can control one pin perfectly, I am now trying  to get another pin discovered so understand it needs a second ESP2866WebServer as well as  a second friendlyname, serial and UUID.  The bit that throws me is the modification of the handleUpnpControl and he For function on the loop to identify which GPIO pin I am working with.
If you have time is there any chance of an expansion on this, what elements need duplicating and renaming and what does the For function need to include?

**Comment by torinnguyen** [comment]
The steps are already outlined in README. I can't help you with actual coding.
